### ISSUE TITLE
sidewinder-x6-macro-keys process takes 99% cpu

### ISSUE THREAD

**Issue by cmavr8** [Wattos/LinuxSidewinderX6#5]
After some time running ok, the process uses a whole CPU core.
It must be a bug but how would I debug it?

The program keeps functioning OK.

This happens on an Ubuntu 12.04 64-bit installation. Used to happen in 11.10, too.

**Comment by Wattos** [comment]
Thanks for note. Ill check it as soon as I have some time on my hands. I just saw it as well

**Comment by Drumm-** [comment]
I am also seeing this. Anybody got any ideas? I'm going to take a look through the source when I get a chance over the next few days.

**Comment by Wattos** [comment]
The bug can only be in two placed. Its either in the main loop:

``` c
    while (_sidewinder_run) {
        sidewinder_handle_keypress();
        if(_sidewinder_keyboard_handle == NULL){
            sidewinder_find_keyboard();
        }
    }
```

or here

``` c
do {
        _sidewinder_keyboard_handle = libusb_open_device_with_vid_pid(_sidewinder_usb_context, SIDEWINDER_VID, SIDEWINDER_PID);
        if(_sidewinder_keyboard_handle <= 0){
            syslog(LOG_INFO, "Could not find the keyboard. Will retry");
            sleep(5);
        }
        else {
            if(_sidewinder_current_profile < 0){
                libusb_detach_kernel_driver(_sidewinder_keyboard_handle, 0);
                libusb_reset_device(_sidewinder_keyboard_handle);
                libusb_attach_kernel_driver(_sidewinder_keyboard_handle, 0);
                sidewinder_set_profile(0);              
            }           
            _sidewinder_lastpress = 0;
            break;
        }
    } while(_sidewinder_keyboard_handle <= 0);
```

basically, what seems to be happening is that one of those for loops get stuck and is looping without any delay

**Comment by Drumm-** [comment]
That will be a huge help. I have some free time on my hands for the next few days, I'll attach a debugger and see what I come up with.

**Comment by Wattos** [comment]
After having another look at the code, I think the issue lies in this loop:

``` c
       while (_sidewinder_run) {
        sidewinder_handle_keypress();
        if(_sidewinder_keyboard_handle == NULL){
            sidewinder_find_keyboard();
        }
    }
```

Normally, **sidewinder_handle_keypress();** is a blocking call (it waits for the user to press a key). The call can however finish immediately when there is an error (e.g. keyboard not present). In this case we assume that the keyboard is not present and try to grab it. But maybe there is a different error happening in **sidewinder_handle_keypress();** which is not being handled correctly (maybe there is another driver running and fighting with us). In this case the driver keeps failing in getting a keypress and is stuck in the loop iterating as fast as possible causing the CPU spike.

**Comment by Drumm-** [comment]
Seems to jump in the CPU usage after a macro key is first triggered. Seems to idle quite contently before this point. So that should help narrow it down under your condition. I believe you are likely correct. It must block until after the first keypress, at which point it's unable to block for whatever reason.

EDIT: I am seeing the following message in my logs: Jul 23 21:25:00 localhost kernel: [255637.448305] usb 3-2: usbfs: process 31302 (sidewinderx6) did not claim interface 1 before use
Might be related. 

EDIT2: Inserted some debug code onto the else clause in sidewinder_handle_keypress(), doesn't seem to be falling over on it's face each run after the first macro is run. Issue might be elsewhere.

**Comment by Wattos** [comment]
@Drumm 

Any luck finding the bug?

**Comment by Drumm-** [comment]
Unfortunately no, not much to add since the little debugging I did a few days ago. Do you know anything about the not claiming interface thing?

**Comment by finndo77** [comment]
Sorry, I cannot help with debugging, but I'd be happy to do some testing if you want to make some changes and update the source on here.  I am just about to plug my x6 in for the first time on my linux machine, and will be doing so after installing this.

I know it is a bit archaic, and similar to what you already did, but back in the early 80's when my dad was writing programs for the US gov social security admin, he would add lines that printed echo statements to the terminal at various stages of the code (the echo was the current line number), like every 50 lines, it might be a major pain to do it, but take a clean copy of the source and add in something like that every so many lines, then compile and run from a terminal and see what happens, once you get to a point where the 99% CPU happens, you can view the output in the terminal to see what section it is either looping, or stopped after, then just remove the others and add more (say the output stopped showing "line 150 executing" you could remove 50 & 100 echo lines, then add in 160, 170, 180, 190 and compile again, then say it stopped out put on line 180, you could add 181, 182, 183, 184, 185, 186, 187, 188, 189... at this point do to the fact the issue is high CPU usage, you should see 1 or more echo lines repeating in the terminal screen, if it is not a single line loop, if it is a single line loop and you still can't figure out what line, again edit the code based off the last line number repeated. 

 It is a pain in the arse, but... when all else fails, it is a pretty darn successful debug method, when you don't know what is causing the problem.  you just have to be methodical about setting the echo lines up, and not randomly scattering them all over.  (if your code is more than a couple hundred lines, you can always do 100 at a time, instead of 50's)  also, if you are compiling off multiple source code files, make sure to add a unique reference that tells you which source file the line came from.

**Comment by Drumm-** [comment]
finndo: This is a method I have been taking. 
Wattos: I am fairly confident that those 2 loops you identified are not what are causing this issue unfortunately. I have added the line - syslog(LOG_DEBUG, "Loop test!") into those loops, outside of any if statements and monitored my /var/log/everything.log file. I can see them being triggered when the loop should be run, but no repeated looping. I am apparently going to have to spend more time working my way backwards. 

EDIT: Interesting spin to this issue I have just noticed if I have a (near) blank .sh file, there is no infinite loop caused. So I have S2.sh to just contain #!/bin/bash and no more. No infinite loop created. S1.sh contains the xscreensaver locking command, and this does cause a loop. 

EDIT 2: Okay, S2.sh was updated to contain notify-send "S2" "This is S2 being run.. K?" and there was no infinite loop being caused. This is most peculiar. However, S1.sh still causes the loop.

EDIT 3: I have now added debug to _most_ for and while loops. I don't seem to be able to find anything in these. Which leads me to believe the issue is elsewhere.

**Comment by 503Dev** [comment]
I am getting an identical issue on Linux Mint 13, which is Ubuntu 12.04 64 bit based.

Runs fine, works fine but after I trigger a Macro my usage jumps to 99% on the process.

Any ideas on how to continue to debug this or fix it.  I have had no luck so far and there is no other driver for linux.

**Comment by Wattos** [comment]
Thanks for being ultra patient with me and this issue. 

Can you try to run the driver with the -f argument? This will run it in the foreground. It appears that if the driver is called with -f, this issue does not happen or at least I was not able to reproduce. 

Can any of you verify that this is the case?

**Comment by 503Dev** [comment]
Hello Wattos,

Thanks a ton for reply. I know you are probably super busy and this is a side project for you - so thank you.  If you have a paypal donate button please link me, i'd love to help.  Your project is my sole hope at using my sidewinder in *nix hah!

I will run it with the -f and update anything I find.

**Comment by 503Dev** [comment]
Update: After a few minutes of testing (more than enough to make the issue occur normally) -- if I run it in terminal as "sudo ./sidewinder-x6-macro-keys -f" it does not utilize 100% CPU.  I tried launching a few scripts with it, no issue at all.

If I run it normally without the -f flag, the issue repeats after using a macro key the first time.

**Comment by Wattos** [comment]
OK, so while this is not a solution, it is a possible workaround for now. You can run it with an & at the end to make it run in the background. Note, if you just run "sudo ./sidewinder-x6-macro-keys -f &" it will also do the password prompt in the background and the application will never run. To work around that, you can either enter something else first, e.g.
sudo echo "hello"
sudo ./sidewinder-x6-macro-keys -f &

or you can use gksudo or kdesudo instead (shows a window dialog).

Once I have time, I will have a more detailed look on why the daemon mode is being naughty

**Comment by tolga9009** [comment]
Hi, I currently have a fully working kernel module solution for the Sidewinder X4. Yesterday, I've bought a Sidewinder X6 to make it work with the kernel module, too. When I'm done, I'll submit it to the HID Maintainer, so it can get merged to latest Linux kernel. So, one day, your Sidewinder Keyboards will work out-of-the-box ^_^! Check it out at: https://github.com/tolga9009/hid-sidewinder-x4. I'm open for any suggestions / optimizations. Please stay patient, I probably will be done within the next 2 - 3 weeks.
Kudos to Wattos for your drivers! I've learned much from them!

**Comment by cmavr8** [comment]
This has been too long and I am not able to test the fix. Since there are no new reports/unhappy users let's close it. Thanks!
